INSERT INTO design_pattern (id, name, category, description, created_at) VALUES
(UUID_TO_BIN(UUID()), 'Singleton', 'Creational', 'Ensures a class has only one instance and provides a global point of access to it.', NOW()),
(UUID_TO_BIN(UUID()), 'Factory Method', 'Creational', 'Defines an interface for creating an object, but lets subclasses decide which class to instantiate.', NOW()),
(UUID_TO_BIN(UUID()), 'Abstract Factory', 'Creational', 'Provides an interface for creating families of related objects without specifying their concrete classes.', NOW()),
(UUID_TO_BIN(UUID()), 'Builder', 'Creational', 'Separates the construction of a complex object from its representation.', NOW()),
(UUID_TO_BIN(UUID()), 'Prototype', 'Creational', 'Creates new objects by copying an existing instance.', NOW()),

(UUID_TO_BIN(UUID()), 'Adapter', 'Structural', 'Allows incompatible interfaces to work together.', NOW()),
(UUID_TO_BIN(UUID()), 'Bridge', 'Structural', 'Separates an abstraction from its implementation so that they can vary independently.', NOW()),
(UUID_TO_BIN(UUID()), 'Composite', 'Structural', 'Composes objects into tree structures to represent part-whole hierarchies.', NOW()),
(UUID_TO_BIN(UUID()), 'Decorator', 'Structural', 'Adds responsibilities to an object dynamically.', NOW()),
(UUID_TO_BIN(UUID()), 'Facade', 'Structural', 'Provides a unified interface to a set of interfaces in a subsystem.', NOW()),
(UUID_TO_BIN(UUID()), 'Flyweight', 'Structural', 'Uses sharing to support large numbers of fine-grained objects efficiently.', NOW()),
(UUID_TO_BIN(UUID()), 'Proxy', 'Structural', 'Provides a surrogate or placeholder for another object to control access to it.', NOW()),

(UUID_TO_BIN(UUID()), 'Chain of Responsibility', 'Behavioral', 'Avoids coupling the sender of a request to its receiver by giving multiple objects a chance to handle the request.', NOW()),
(UUID_TO_BIN(UUID()), 'Command', 'Behavioral', 'Encapsulates a request as an object, allowing you to parameterize clients with different requests.', NOW()),
(UUID_TO_BIN(UUID()), 'Interpreter', 'Behavioral', 'Gives a grammatical representation of a language and uses an interpreter to interpret it.', NOW()),
(UUID_TO_BIN(UUID()), 'Iterator', 'Behavioral', 'Provides a way to access elements of an aggregate object sequentially without exposing its underlying representation.', NOW()),
(UUID_TO_BIN(UUID()), 'Mediator', 'Behavioral', 'Defines an object that encapsulates how a set of objects interact.', NOW()),
(UUID_TO_BIN(UUID()), 'Memento', 'Behavioral', 'Captures and externalizes an object’s internal state without violating encapsulation.', NOW()),
(UUID_TO_BIN(UUID()), 'Observer', 'Behavioral', 'Defines a one-to-many dependency so that when one object changes state, all its dependents are notified.', NOW()),
(UUID_TO_BIN(UUID()), 'State', 'Behavioral', 'Allows an object to alter its behavior when its internal state changes.', NOW()),
(UUID_TO_BIN(UUID()), 'Strategy', 'Behavioral', 'Defines a family of algorithms, encapsulates each one, and makes them interchangeable.', NOW()),
(UUID_TO_BIN(UUID()), 'Template Method', 'Behavioral', 'Defines the skeleton of an algorithm and lets subclasses override specific steps.', NOW()),
(UUID_TO_BIN(UUID()), 'Visitor', 'Behavioral', 'Represents an operation to be performed on elements of an object structure.', NOW());
