INSERT INTO design_pattern (id, name, category, description, created_at) VALUES
(UUID_TO_BIN(UUID()), 'Singleton', 'Criacional', 'Garante que uma classe tenha apenas uma instância e fornece um ponto global de acesso a ela.', NOW()),
(UUID_TO_BIN(UUID()), 'Factory Method', 'Criacional', 'Define uma interface para criar um objeto, mas deixa as subclasses decidirem qual classe instanciar.', NOW()),
(UUID_TO_BIN(UUID()), 'Abstract Factory', 'Criacional', 'Fornece uma interface para criar famílias de objetos relacionados sem especificar suas classes concretas.', NOW()),
(UUID_TO_BIN(UUID()), 'Builder', 'Criacional', 'Separa a construção de um objeto complexo da sua representação.', NOW()),
(UUID_TO_BIN(UUID()), 'Prototype', 'Criacional', 'Cria novos objetos copiando uma instância existente.', NOW()),

(UUID_TO_BIN(UUID()), 'Adapter', 'Estrutural', 'Permite que interfaces incompatíveis trabalhem juntas.', NOW()),
(UUID_TO_BIN(UUID()), 'Bridge', 'Estrutural', 'Separa uma abstração da sua implementação para que possam variar independentemente.', NOW()),
(UUID_TO_BIN(UUID()), 'Composite', 'Estrutural', 'Compõe objetos em estruturas de árvore para representar hierarquias parte-todo.', NOW()),
(UUID_TO_BIN(UUID()), 'Decorator', 'Estrutural', 'Adiciona responsabilidades a um objeto dinamicamente.', NOW()),
(UUID_TO_BIN(UUID()), 'Facade', 'Estrutural', 'Fornece uma interface unificada para um conjunto de interfaces em um subsistema.', NOW()),
(UUID_TO_BIN(UUID()), 'Flyweight', 'Estrutural', 'Usa o compartilhamento para suportar grandes quantidades de objetos de forma eficiente.', NOW()),
(UUID_TO_BIN(UUID()), 'Proxy', 'Estrutural', 'Fornece um substituto ou representante de outro objeto para controlar o acesso a ele.', NOW()),

(UUID_TO_BIN(UUID()), 'Chain of Responsibility', 'Comportamental', 'Evita acoplamento do remetente de uma solicitação ao seu receptor ao dar a mais de um objeto a chance de tratar a solicitação.', NOW()),
(UUID_TO_BIN(UUID()), 'Command', 'Comportamental', 'Encapsula uma solicitação como um objeto, permitindo parametrizar clientes com diferentes solicitações.', NOW()),
(UUID_TO_BIN(UUID()), 'Interpreter', 'Comportamental', 'Dá uma representação gramatical a uma linguagem e usa um interpretador para interpretá-la.', NOW()),
(UUID_TO_BIN(UUID()), 'Iterator', 'Comportamental', 'Fornece uma maneira de acessar os elementos de um objeto agregado sequencialmente sem expor sua representação subjacente.', NOW()),
(UUID_TO_BIN(UUID()), 'Mediator', 'Comportamental', 'Define um objeto que encapsula como um conjunto de objetos interage.', NOW()),
(UUID_TO_BIN(UUID()), 'Memento', 'Comportamental', 'Captura e externaliza o estado interno de um objeto sem violar o encapsulamento.', NOW()),
(UUID_TO_BIN(UUID()), 'Observer', 'Comportamental', 'Define uma dependência um-para-muitos entre objetos de modo que quando um objeto muda de estado, todos os seus dependentes são notificados.', NOW()),
(UUID_TO_BIN(UUID()), 'State', 'Comportamental', 'Permite que um objeto altere seu comportamento quando seu estado interno muda.', NOW()),
(UUID_TO_BIN(UUID()), 'Strategy', 'Comportamental', 'Define uma família de algoritmos, encapsula cada um e os torna intercambiáveis.', NOW()),
(UUID_TO_BIN(UUID()), 'Template Method', 'Comportamental', 'Define o esqueleto de um algoritmo na operação, postergando alguns passos para subclasses.', NOW()),
(UUID_TO_BIN(UUID()), 'Visitor', 'Comportamental', 'Representa uma operação a ser realizada nos elementos de uma estrutura de objeto.', NOW());