spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trophy_lab_backend
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations
    schemas: trophy_lab_backend
    validate-on-migrate: true

server:
  port: 8080

open-ai:
  api-key: ${OPENAI_API_KEY}
  project-id: ${OPENAI_PROJECT_ID}
  organization-id: ${OPENAI_ORG_ID}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example: DEBUG
    org.flywaydb: INFO