spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations
    schemas: daily_pattern_backend
    validate-on-migrate: true

server:
  port: 8080

open-ai:
  api-key: ${OPENAI_API_KEY}
  project-id: ${OPENAI_PROJECT_ID}
  organization-id: ${OPENAI_ORG_ID}

jwt:
  secret-key: ${JWT_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example: DEBUG
    org.flywaydb: INFO